// <auto-generated />
namespace ProductService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class name1onsupplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name1onsupplier));
        
        string IMigrationMetadata.Id
        {
            get { return "201603220823468_name1onsupplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
